#a sample docker-compose yml, contain postgresql, redis, rabbitmq, NEXT.js app
version: '3.7'
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - postgres
      - redis
      - rabbitmq